version: 2

jobs:
  build:
    docker:
      - image: crystallang:crystal
    steps:
      - checkout
      - run:
          name: Build
          command: shards build

workflows:
  test:
    jobs:
      test:
        docker:
          - image: crystallang:crystal
        steps:
          - checkout
          - run:
              name: Test
              command: crystal spec
